# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_list_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default
  database: todo_list_production
  username: todo_list
  password: <%= ENV['TODO_LIST_DATABASE_PASSWORD'] %>
